Assigning Values to variables

In [ ]:
x <- 10
print(x)
y <- "Hello"
print(y)
z <- TRUE
print(z)

[1] 10
[1] "Hello"
[1] TRUE


In [ ]:
var1 <- 5
var1.name <- 10
print(var1)
print(var1.name)

[1] 5
[1] 10


In [ ]:
5 -> varr
10 -> Varr
print(varr)
print(Varr)

[1] 5
[1] 10


In [ ]:
assign("c",TRUE)
print(c)

[1] TRUE


Dynamic Typing

In [ ]:
x <- 20
print(x)
x <- "R - Programming"
print(x)

[1] 20
[1] "R - Programming"


Comments

In [ ]:
#This is single line comment
#Alternatively :
x <- 10
if(FALSE){
  #This block is not executed
  x <- x + 5
}
print(x)

[1] 10


if-else

In [ ]:
x <- 10
if (x > 5) {
 print("x is greater than 5")
} else {
 print("x is less than or equal to 5")
}

[1] "x is greater than 5"


for loop

In [ ]:
for (i in 1:5) {
 print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


while loop

In [ ]:
count <- 1
while(count <= 3){
    print(paste("Count is",count))
    count <- count + 1
}

[1] "Count is 1"
[1] "Count is 2"
[1] "Count is 3"


In [ ]:
square <- function(x){
    return (x * x)
}
print(square(8))

[1] 64


break keyword

In [ ]:
for (i in 1:10) {
 if (i == 6) {
 break
 }
 print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


next keyword(like continue)

In [ ]:
for (i in 1:5){
    if(i == 3){
        next
    }
    print(i)
}

[1] 1
[1] 2
[1] 4
[1] 5


Operators

In [ ]:
a <- 10
b <- 3
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a %% b)
print(a %/% b)

[1] 13
[1] 7
[1] 30
[1] 3.333333
[1] 1
[1] 3


In [ ]:
x <- 10
y <- 5
print(x == y)
print(x != y)
print(x > y)
print(x < y)
print(x >= y)
print(x <= y)

[1] FALSE
[1] TRUE
[1] TRUE
[1] FALSE
[1] TRUE
[1] FALSE


In [ ]:
a <- TRUE
b <- FALSE
print(a & b)
print(a | b)
print(!a)
print(a && b)
print(a || b)

[1] FALSE
[1] TRUE
[1] FALSE
[1] FALSE
[1] TRUE


In [ ]:
x <- 10
20 -> y
z = 30
print(x)
print(y)
print(z)

[1] 10
[1] 20
[1] 30


In [ ]:
seq <- 1:5
print(seq)

[1] 1 2 3 4 5


In [ ]:
print(3 %in% c(1,2,3))
print(4 %in% c(1,2,5,6))

[1] TRUE
[1] FALSE


In [ ]:
mat1 <- matrix(1:4,nrow=2)
print(mat1)
mat2 <- matrix(5:8,nrow=2)
print(mat2)
print(mat1 %*% mat2)

     [,1] [,2]
[1,]    1    3
[2,]    2    4
     [,1] [,2]
[1,]    5    7
[2,]    6    8
     [,1] [,2]
[1,]   23   31
[2,]   34   46


R Data types

In [ ]:
num <- 10.5
x <- 5L
char <- "Hello"
bool <- TRUE
comp <- 5 + 6i
print(class(num))
print(class(x))
print(class(char))
print(class(bool))
print(class(comp))

[1] "numeric"
[1] "integer"
[1] "character"
[1] "logical"
[1] "complex"


In [ ]:
x <- NULL
y <- NA
z <- Inf
w <- NaN
print(x)
print(y)
print(z)
print(w)

NULL
[1] NA
[1] Inf
[1] NaN


In [ ]:
vec <- c(1,2,3)
print(vec)

[1] 1 2 3


In [ ]:
lst <- list(2,"a",TRUE)
print(lst)

[[1]]
[1] 2

[[2]]
[1] "a"

[[3]]
[1] TRUE



In [ ]:
df = data.frame(name=c("Rakesh","Rajesh"),age=c(18,20))
print(df)

    name age
1 Rakesh  18
2 Rajesh  20


In [ ]:
fac <- factor(c("A","B","C","B"))
print(fac)

[1] A B C B
Levels: A B C


In [ ]:
grades <- factor(c("A", "B", "A", "C","B","A","B","C"), levels = c("A", "B", "C", "D"))
print(grades)

[1] A B A C B A B C
Levels: A B C D


In [ ]:
responses <- c("iPhone", "Samsung", "iPhone", "Xiaomi", "Samsung")
all_brands <- c("iPhone", "Samsung", "Google", "Xiaomi", "OnePlus")
phone_factor <- factor(responses, levels = all_brands)
print(phone_factor)

[1] iPhone  Samsung iPhone  Xiaomi  Samsung
Levels: iPhone Samsung Google Xiaomi OnePlus


In [ ]:
table(phone_factor)

phone_factor
 iPhone Samsung  Google  Xiaomi OnePlus 
      2       2       0       1       0 

In [ ]:
temperature <- factor(
 c("Low", "High", "Medium", "Low"),
 levels = c("Low", "Medium", "High"),
 ordered = TRUE
)
print(temperature)


colors <- factor(c("Red", "Blue", "Green"))
print(levels(colors)) # "Blue" "Green" "Red"
# Change levels
levels(colors) <- c("R", "B", "G")
print(colors) # R B

[1] Low    High   Medium Low   
Levels: Low < Medium < High
[1] "Blue"  "Green" "Red"  
[1] G R B
Levels: R B G


In [ ]:
f <- factor(c("Apple", "Banana", "Apple"))
print(as.character(f)) # "Apple" "Banana" "Apple"
print(as.numeric(f)) # 1 2 1 (internal codes)

[1] "Apple"  "Banana" "Apple" 
[1] 1 2 1


In [ ]:
f <- factor(c("A", "B", "A", "C"), levels = c("A", "B", "C", "D"))
f_new <- factor(f, levels = c("A", "B")) # Drops "C" and "D"
print(f_new) # A B A <NA>
# Remove unused levels
f_clean <- droplevels(f)
print(f_clean) # Levels: A B C

[1] A    B    A    <NA>
Levels: A B
[1] A B A C
Levels: A B C


In [ ]:
data <- data.frame(
 yield = c(10, 15, 12, 20),
 fertilizer = factor(c("A", "B", "A", "B"))
)
model <- lm(yield ~ fertilizer, data = data)
summary(model) # Compares A (baseline) vs. B


Call:
lm(formula = yield ~ fertilizer, data = data)

Residuals:
   1    2    3    4 
-1.0 -2.5  1.0  2.5 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)  
(Intercept)   11.000      1.904   5.777   0.0287 *
fertilizerB    6.500      2.693   2.414   0.1372  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 2.693 on 2 degrees of freedom
Multiple R-squared:  0.7445,	Adjusted R-squared:  0.6167 
F-statistic: 5.828 on 1 and 2 DF,  p-value: 0.1372


In [ ]:
data$fertilizer <- reorder(data$fertilizer, data$yield, FUN = mean)
print(levels(data$fertilizer)) # Sorted by mean yiel

[1] "A" "B"
