In [1]:
list1 <- list(1, 2, 3)

In [3]:
list2 <- list("water", "juice", "lemonade")

In [4]:
print(list1)
print(list2)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[1]]
[1] "water"

[[2]]
[1] "juice"

[[3]]
[1] "lemonade"



In [5]:
list12 <- c(list1, list2)

In [6]:
print(list12)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] "water"

[[5]]
[1] "juice"

[[6]]
[1] "lemonade"



In [7]:
print(unlist(list1))

[1] 1 2 3


In [8]:
print(unlist(list2))

[1] "water"    "juice"    "lemonade"


In [9]:
print(mode(list1))

[1] "list"


In [10]:
print(mode(unlist(list1)))

[1] "numeric"


In [11]:
print(append(list1, 100))

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 100



In [12]:
print(append(list2, "coffee"))

[[1]]
[1] "water"

[[2]]
[1] "juice"

[[3]]
[1] "lemonade"

[[4]]
[1] "coffee"



In [13]:
print(append(list1, 100, after = 2))

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 100

[[4]]
[1] 3



In [14]:
print(append(list2, "coffee", after = 2))

[[1]]
[1] "water"

[[2]]
[1] "juice"

[[3]]
[1] "coffee"

[[4]]
[1] "lemonade"



In [15]:
print(list1[-2])

[[1]]
[1] 1

[[2]]
[1] 3



In [16]:
print(list2[-1])

[[1]]
[1] "juice"

[[2]]
[1] "lemonade"



In [17]:
list1 <- list(1, 2, 3, 4, 5, 6)

In [18]:
list2 <- list(
  "water",
  "juice",
  "lemonade",
  "tea",
  "coffee",
  "milk"
)

In [19]:
print(list1)
print(list2)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] 5

[[6]]
[1] 6

[[1]]
[1] "water"

[[2]]
[1] "juice"

[[3]]
[1] "lemonade"

[[4]]
[1] "tea"

[[5]]
[1] "coffee"

[[6]]
[1] "milk"



In [20]:
print(list1[2:4])
print(list2[2:4])

[[1]]
[1] 2

[[2]]
[1] 3

[[3]]
[1] 4

[[1]]
[1] "juice"

[[2]]
[1] "lemonade"

[[3]]
[1] "tea"



In [21]:
print(list1[c(1, 3, 5)])

print(list2[c(1, 3, 5)])

[[1]]
[1] 1

[[2]]
[1] 3

[[3]]
[1] 5

[[1]]
[1] "water"

[[2]]
[1] "lemonade"

[[3]]
[1] "coffee"



In [22]:
x <- 1:10

print(x)

 [1]  1  2  3  4  5  6  7  8  9 10


In [23]:
print(x[x > 5])

[1]  6  7  8  9 10


In [24]:
print(x[x %% 2 == 0])

[1]  2  4  6  8 10


In [25]:
print(x[x %% 2 == 1])

[1] 1 3 5 7 9


In [26]:
x <- 1:10

x[5] <- NA

print(x)

 [1]  1  2  3  4 NA  6  7  8  9 10


In [27]:
y <- x[!is.na(x)]

print(y)

[1]  1  2  3  4  6  7  8  9 10


In [28]:
print(mean(x))

[1] NA


In [29]:
print(mean(y))

[1] 5.555556


In [30]:
x <- 1:10

print(x[-(1:5)])

[1]  6  7  8  9 10


In [31]:
print(x[6:10])

[1]  6  7  8  9 10


In [33]:
z <- list(
  a1 = 1,
  a2 = "c",
  a3 = 1:3
)
print(z)

$a1
[1] 1

$a2
[1] "c"

$a3
[1] 1 2 3



In [34]:
print(names(z))

[1] "a1" "a2" "a3"


In [35]:
names(z)[3] <- "c2"

print(z)

$a1
[1] 1

$a2
[1] "c"

$c2
[1] 1 2 3



In [36]:
x <- c(
  water = 1,
  juice = 2,
  lemonade = 3
)

print(x)

   water    juice lemonade 
       1        2        3 


In [37]:
print(names(x))

[1] "water"    "juice"    "lemonade"


In [38]:
print(x["juice"])

juice 
    2 


In [39]:
x <- 1:10

print(x)

print(x[])

 [1]  1  2  3  4  5  6  7  8  9 10
 [1]  1  2  3  4  5  6  7  8  9 10


In [40]:
ab <- list(
  1,
  2,
  3,
  "X",
  "Y",
  "Z"
)
print(ab)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] "X"

[[5]]
[1] "Y"

[[6]]
[1] "Z"



In [41]:
dim(ab) <- c(2, 3)

print(ab)

     [,1] [,2] [,3]
[1,] 1    3    "Y" 
[2,] 2    "X"  "Z" 


In [42]:
print(mode(ab))

[1] "list"


In [45]:
x <- factor(
  c(
    "lemonade",
    "lemonade",
    "juice",
    "lemonade",
    "water"
  )
)
print(x)

[1] lemonade lemonade juice    lemonade water   
Levels: juice lemonade water


In [46]:
print(levels(x))

[1] "juice"    "lemonade" "water"   


In [47]:
x <- c(
  3, 4, 5, 6,
  1, 2, 3, 3,
  4, 4, 5, 6
)

y <- as.factor(x)
print(y)

 [1] 3 4 5 6 1 2 3 3 4 4 5 6
Levels: 1 2 3 4 5 6


In [48]:
print(levels(y))

[1] "1" "2" "3" "4" "5" "6"


In [49]:
y <- c(
  1, 4, 3, 5,
  4, 2, 4
)

print(y)

[1] 1 4 3 5 4 2 4


In [50]:
possible.dieface <- c(
  1, 2, 3, 4, 5, 6
)

print(possible.dieface)

[1] 1 2 3 4 5 6


In [51]:
labels.dieface <- c(
  "one",
  "two",
  "three",
  "four",
  "five",
  "six"
)
print(labels.dieface)

[1] "one"   "two"   "three" "four"  "five"  "six"  


In [52]:
facy <- factor(
  y,
  levels = possible.dieface,
  labels = labels.dieface
)

print(facy)

[1] one   four  three five  four  two   four 
Levels: one two three four five six


In [53]:
print(levels(facy))

[1] "one"   "two"   "three" "four"  "five"  "six"  


In [54]:
print(class(9))

print(class("9"))

print(class(print))

[1] "numeric"
[1] "character"
[1] "function"


In [56]:
x <- matrix(
  nrow = 2,
  ncol = 2,
  data = 1:4
)

print(x)

print(class(x))

     [,1] [,2]
[1,]    1    3
[2,]    2    4
[1] "matrix" "array" 


In [57]:
brands <- c(
  "A",
  "A",
  "B",
  "B",
  "B",
  "B",
  "C"
)

brands_fac <- factor(brands)

print(brands_fac)

[1] A A B B B B C
Levels: A B C


In [58]:
print(unclass(brands_fac))

[1] 1 1 2 2 2 2 3
attr(,"levels")
[1] "A" "B" "C"


In [59]:
colours <- c(
  "blue",
  "green",
  "red"
)

print(colours)

[1] "blue"  "green" "red"  


In [60]:
print(colours[unclass(brands_fac)])

[1] "blue"  "blue"  "green" "green" "green" "green" "red"  


In [61]:
x <- factor(
  c(
    "lemonade",
    "lemonade",
    "juice",
    "lemonade",
    "water"
  ),
  levels = c(
    "water",
    "juice",
    "lemonade"
  )
)

print(x)

[1] lemonade lemonade juice    lemonade water   
Levels: water juice lemonade


In [62]:
print(levels(x))

[1] "water"    "juice"    "lemonade"


In [63]:
print(unclass(x))

[1] 3 3 2 3 1
attr(,"levels")
[1] "water"    "juice"    "lemonade"


In [64]:
income <- ordered(
  c(
    "high",
    "high",
    "low",
    "medium",
    "medium"
  ),
  levels = c(
    "low",
    "medium",
    "high"
  )
)

print(income)

[1] high   high   low    medium medium
Levels: low < medium < high


In [65]:
print(levels(income))

[1] "low"    "medium" "high"  


In [66]:
print(unclass(income))

[1] 3 3 1 2 2
attr(,"levels")
[1] "low"    "medium" "high"  


In [67]:
print(sqrt(2))

[1] 1.414214


In [68]:
print(sqrt(2), digits = 5)

print(sqrt(2), digits = 10)

[1] 1.4142
[1] 1.414213562


In [69]:
print("apple")

print(c("apple", "banana"))

print(c("apple", "banana", 6, 10))

[1] "apple"
[1] "apple"  "banana"
[1] "apple"  "banana" "6"      "10"    


In [70]:
print(format(0.5))

[1] "0.5"


In [71]:
print(
  format(
    0.5,
    digits = 10,
    nsmall = 15
  )
)

[1] "0.500000000000000"


In [72]:
print(
  format(
    c("A", "BB", "CCC", "DDDD"),
    width = 7,
    justify = "centre"
  )
)

[1] "   A   " "  BB   " "  CCC  " " DDDD  "


In [73]:
print(
  format(
    c("A", "BB", "CCC", "DDDD"),
    width = 7,
    justify = "left"
  )
)

[1] "A      " "BB     " "CCC    " "DDDD   "


In [74]:
print(
  format(
    c("A", "BB", "CCC", "DDDD"),
    width = 7,
    justify = "right"
  )
)

[1] "      A" "     BB" "    CCC" "   DDDD"


In [75]:
print(
  format(
    c("A", "BB", "CCC", "DDDD"),
    width = 7,
    justify = "none"
  )
)

[1] "A"    "BB"   "CCC"  "DDDD"


In [76]:
x <- matrix(
  nrow = 3,
  ncol = 2,
  data = 1:6,
  byrow = TRUE
)

print(x)

     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6


In [77]:
print(
  format(
    1234567,
    big.mark = ","
  )
)

[1] "1,234,567"


In [78]:
print(
  format(
    12345678,
    big.mark = ","
  )
)

print(
  format(
    123456789,
    big.mark = ","
  )
)

[1] "12,345,678"
[1] "123,456,789"


In [79]:
print(
  format(
    123456789,
    big.mark = " "
  )
)

[1] "123 456 789"
